name: build
on:
  push:
    branches: [ main ]
jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pip install
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install panel
      - name: panel convert
        run: |
          python -m panel convert public_office.py --to pyodide-worker --out .
      - uses: stefanzweifel/git-auto-commit-action@v4